
export interface Entregador {
  "active": boolean,
  "anoVeiculo": number,
  "bairro": string,
  "categoriaCNH": string,
  "celular": string,
  "cep": string,
  "cidade": string,
  "complemento": string,
  "corVeiculo": string,
  "cpf": string,
  "dataNascimento": string,
  "dataUltimaRotaRealizada": string,
  "dataUltimaVezOnline": string,
  "deleted": true,
  "email": string,
  "estadoCivil": string,
  "exibirFotoPerfil": true,
  "expiracaoCNH": string,
  "id": number,
  "logradouro": string,
  "marcaVeiculo": string,
  "matricula": string,
  "modeloVeiculo": string,
  "nome": string,
  "numeroCNH": string,
  "numeroEndereco": string,
  "online": true,
  "placaVeiculo": string,
  "referencia": string,
  "status": string,
  "tenant": {
    "active": true,
    "cooperativeCode": string,
    "createdAt": string,
    "id": number,
    "lastUpdate": string,
    "name": string
  },
  "uf": string,
  "urlFotoCNH": string,
  "urlFotoDocumentoVeiculo": string,
  "urlFotoPerfil": string
}
